"""Game constants and configuration"""

import math

# Window settings
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 800

# Car dimensions
CAR_LENGTH = 15 * 2.5
CAR_WIDTH = 15 * 1.2
CAR_HEIGHT = 10

# Road settings
ROAD_WIDTH = 400
BORDER_HEIGHT = 30.0
BORDER_THICKNESS = 12.0

# Movement speeds
NORMAL_SPEED = 15.0
BOOST_SPEED = 20.0
SLOW_SPEED = 10.0
TURN_SPEED = 3

# Camera settings
CAMERA_OFFSET = [0, -150, 75]
FOV_Y = 60

# Physics
GRAVITY = 9.81
MAX_Z_VELOCITY = 20

# Game settings
INITIAL_LIVES = 10
NUM_ENEMY_CARS = 3
INITIAL_NUM_TREES = 50
MAX_WORLD_SIZE = 10000

# Procedural generation defaults
MIN_TRACK_LENGTH = 1000
MAX_TRACK_LENGTH = 3000
MIN_CURVE_RADIUS = 200
MAX_CURVE_RADIUS = 600

# Collision detection
COLLISION_TOLERANCE = 0

# Rendering
TREE_HEIGHT = 60
TREE_TRUNK_RADIUS = 10
TREE_CROWN_BASE_RADIUS = 40
